name = "dkg-entertainment"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "dkg-db"
database_id = "7cfa29a6-f697-4ec1-b5e9-0c553580d854"

[[r2_buckets]]
binding = "R2"
bucket_name = "dkg-uploads"
